version: '3.1'

services:

  ihm-studentlist:
    depends_on:
      - studentlist
    image: php:apache
    restart: always
    container_name: ihm-studentlist
    ports:
      - 6000:80
    environment:
      USERNAME: toto
      PASSWORD: python
    volumes:
      - ./website:/var/www/html
    networks:
      - bootcamp16

  studentlist:

    image: bootcamp16-student-list
    container_name: studentlist
    restart: always
    volumes:
      - ${PWD}/simple_api/student_age.json:/data/student_age.json
    networks:
     - bootcamp16

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
     - 5000:5000
    networks:
     - bootcamp16
  
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Bootcamp16 registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    networks:
     - bootcamp16

networks:
  bootcamp16:
