version: '3.1'

services:

  ihm-student-list:
    depends_on:
      - api-student-list
    image: php:apache
    restart: always
    container_name: ihm-student-list
    ports:
      - 80:80
    environment:
      USERNAME: toto
      PASSWORD: python
    volumes:
      - ./website:/var/www/html
    networks:
      - student-list-net

  api-student-list:

    image: student-list
    container_name: api-student-list
    restart: always
    volumes:
      - ${PWD}/simple_api/student_age.json:/data/student_age.json
    networks:
     - student-list-net

  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
     - 6000:5000
    networks:
     - student-list-net
  
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8000:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=student_list registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    networks:
     - student-list-net

networks:
  student-list-net:
